<?php
/**
 * @var \M2E\Temu\Block\Adminhtml\Category\CategoryChooser $block
 */
?>

<div id='category_info_messaged_container'></div>

<div class="control-value">
    <?= /* @noEscape */ __(
        'You need to choose Categories for Products in order to list them on %channel_title.',
        [
            'channel_title' => \M2E\Temu\Helper\Module::getChannelTitle(),
        ],
    ) ?>
</div>

<div style="padding-top: 3px; font-weight: normal">
    <?= /* @noEscape */ __(
        'Products will be Listed using the same %channel_title Category.',
        [
            'channel_title' => \M2E\Temu\Helper\Module::getChannelTitle(),
        ],
    ) ?>
</div>

<div style="margin: 7px 52px">
    <b><?= /* @noEscape */ __('Category') ?></b>:
    <span id="category_path" style="font-style: italic; color: #808080">Not selected</span>
    &nbsp;<a href="javascript:void(0);" id="edit_category"><?= /* @noEscape */ __('Edit') ?></a>
    <br>
    <div id="attributes_wrapper" class="hidden">
        <b><?= /* @noEscape */ __('Title') ?></b>:
        <span class="dictionary_title_wrapper">
            <span id="dictionary_title" style="font-style: italic; color: #808080"></span>
            &nbsp<a href="javascript:void(0);" id="edit_title"><?= /* @noEscape */ __('Edit') ?></a>
        </span>
        <span class="dictionary_title_edit_wrapper" style="display: none;">
            <input type="text" id="dictionary_title_input" class="input-text admin__control-text" style="min-width: 400px;">
            &nbsp<a href="javascript:void(0);" id="save_title"><?= /* @noEscape */ __('Save') ?></a>
            &nbsp<a href="javascript:void(0);" id="cancel_save_title"><?= /* @noEscape */ __('Cancel') ?></a>
        </span>
        <br>
        <b><?= /* @noEscape */ __('Attributes') ?></b>:
        <span id="attributes_required" class="required hidden">*</span>
        <span id="attributes_counts" style="font-style: italic; color: #808080">0/0</span>
        &nbsp<a href="javascript:void(0);" id="edit_attributes"><?= /* @noEscape */ __('Edit') ?></a>
    </div>
</div>
<label style="margin: 0 52px; display: none;" class="mage-error" id="same_product_type_error">
    <?= /* @noEscape */ __('Please select Category.') ?>
</label>

<script>
    require([
        'Temu/Category/Chooser'
    ], function() {
        TemuCategoryChooserObj.resetSelectedData();
        <?php if ($block->isExistCategoryDictionary()): ?>
        TemuCategoryChooserObj.setSelectedCategory(
            <?= /* @noEscape */ $block->getSelectedCategory() ?>,
            <?= /* @noEscape */ $block->getSelectedDictionaryId() ?>
        );
        TemuCategoryChooserObj.confirmCategory()
        <?php endif; ?>
        TemuCategoryChooserObj.initObservers();
    });
</script>
