<?php

/** @var $block \M2E\Temu\Block\Adminhtml\Listing\Wizard\Category\Add\Tree */

?>

<div class="Temu-box-style" style="margin-top: 11px; padding: 10px 15px;">
    <?= /* @noEscape */ __('Selected Products: ') ?><span id="total_products_count">0</span>
    <br/>
    <?= /* @noEscape */ __('Selected Categories: ') ?><span id="total_categories_count">0</span>

    <span id="view_categories_summary">
        (<a href="javascript:" onclick="saveSelectedProducts(showCategoriesSummary)"><?= /* @noEscape */ __('View') ?></a>)
    </span>
</div>

<div class="content-header" style="padding-top: 10px;">
    <h3 class="icon-head head-categories" style="margin-bottom: 10px;"><?= /* @noEscape */ __('Categories'); ?></h3>
</div>

<div class="categories-side-col">
    <div class="tree-holder">
        <div id="tree-div" style="width: 100%; overflow: auto;"></div>
    </div>
</div>

<script>
    require([
        'Magento_Ui/js/modal/modal',
        'jquery',
        'jstree'
    ], function (modal, $) {
        let tree;
        let treeInfo = <?= /* @noEscape */ $block->getInfoJson() ?>;

        createNodeByConfig = function (config) {
            return {
                id: config.id,
                parent: config.parentId || '#',
                text: config.text,
                children: config.children || []
            };
        };

        buildCategoryTree = function (parent, config) {
            if (!config) return;

            if (parent && config && config.length) {
                for (let i = 0; i < config.length; i++) {
                    const node = createNodeByConfig(config[i]);

                    parent.push(node);
                    if (config[i].children) {
                        buildCategoryTree(node.children, config[i].children);
                    }
                }
            }
        };

        categoryClick = function (node, event) {
            const gridObj = window['<?php  /* @noEscape */ echo $block->getGridId() ?>JsObject'];

            saveSelectedProducts(function (transport) {

                gridObj.reloadParams['category_change'] = 1;
                gridObj.reloadParams['current_category_id'] = node.id;
                gridObj.reload();

            });
        };

        updateInfo = function () {
            $('span[category_id]').each(function () {
                const categoryId = $(this).attr('category_id');
                $(this).html(treeInfo['category_products'][categoryId]);
            });

            $('#total_products_count').html(treeInfo['total_products_count']);
            $('#total_categories_count').html(treeInfo['total_categories_count']);

            if (treeInfo['total_categories_count'] > 0) {
                $('#view_categories_summary').show();
            } else {
                $('#view_categories_summary').hide();
            }
        };

        saveSelectedProducts = function (callback) {
            const gridObj = window['<?php  /* @noEscape */ echo $block->getGridId() ?>JsObject'];
            const massGridObj = window['<?php  /* @noEscape */ echo $block->getGridId() ?>_massactionJsObject'];

            const checkedString = massGridObj['checkedString'];
            const initialCheckedString = massGridObj['initialCheckedString'];

            massGridObj['checkedString'] = '';
            massGridObj['initialCheckedString'] = '';

            new Ajax.Request('<?php  /* @noEscape */ echo $block->getUrl(
                '*/*/saveProductsAndGetInfo',
                ['_current' => true]
            ) ?>', {
                method: 'post',
                parameters: {
                    checked_ids: checkedString,
                    initial_checked_ids: initialCheckedString
                },
                onSuccess: function (transport) {
                    treeInfo = transport.responseText.evalJSON();
                    updateInfo();
                    callback && callback(transport);
                    gridObj.reloadParams['category_change'] = 0;
                }
            });
        };

        showCategoriesSummary = function () {
            const gridObj = window['<?= /* @noEscape */ $block->getGridId() ?>JsObject'];
            const massGridObj = window['<?= /* @noEscape */ $block->getGridId() ?>_massactionJsObject'];

            new Ajax.Request('<?= /* @noEscape */ $block->getUrl('*/*/getCategoriesSummaryHtml', ['_current' => true]); ?>', {
                method: 'get',
                parameters: {
                    categories_ids: getExpandedCategoriesIds().join(',')
                },
                onSuccess: function (transport) {
                    if (!$('#Temu-popup').length) {
                        $('body').append('<div id="Temu-popup"></div>');
                    }

                    const popup = $('#Temu-popup');
                    popup.html(transport.responseText);

                    const modalOptions = {
                        title: '<?= /* @noEscape */ __('Categories of selected Magento Products') ?>',
                        type: 'slide',
                        closed: function () {
                            const url = '<?= /* @noEscape */ $block->getUrl('*/*/getTreeInfo', ['_current' => true]); ?>';
                            new Ajax.Request(url, {
                                method: 'get',
                                onSuccess: function (transport) {
                                    treeInfo = transport.responseText.evalJSON();
                                    updateInfo();
                                    massGridObj.unselectAll();
                                    gridObj.reloadParams['category_change'] = 1;
                                    gridObj.reload();
                                    gridObj.reloadParams['category_change'] = 0;
                                }
                            });
                        },
                        buttons: []
                    };

                    modal(modalOptions, popup);

                    popup.modal('openModal');
                }
            });

        };

        closeCategoriesPopup = function () {
            $('#Temu-popup').modal('closeModal');
        };

        getExpandedCategoriesIds = function () {
            const categoriesIds = [];
            $('#tree-div').jstree('get_selected').each(function () {
                categoriesIds.push($(this).attr('id'));
            });
            return categoriesIds;
        };

        $(document).ready(function () {
            const categoryData = <?= /* @noEscape */ $block->getTreeJson() ?>;

            tree = $('#tree-div').jstree({
                'core': {
                    'data': categoryData,
                    'themes': {
                        'name': 'default',
                        'responsive': true
                    }
                }
            });

            $('#tree-div').on("select_node.jstree", function (e, data) {
                categoryClick(data.node, e);
            });

            $('#tree-div').on("click.jstree", function () {
                updateInfo();
            });

            updateInfo();
        });
    });
</script>
