<?php

/** @var \M2E\Temu\Block\Adminhtml\Template\Category\Chooser\Specific\Form\Renderer\Dictionary $block */

/** @var \M2E\Temu\Block\Adminhtml\Template\Category\Chooser\Specific\Form\Element\Dictionary $element */
$element = $block->getElement();
?>

<table
    data-specific-scope="<?= /* @noEscape */ $element->getId() ?>"
    class="specific-table data-grid data-grid-not-hovered"
    style="width: 100%"
>
    <thead>
    <tr class="headings">
        <th class="data-grid-th" style="width: 30%;"><?= /* @noEscape */ __('Name'); ?></th>
        <th class="data-grid-th" style="width: 30%;"><?= /* @noEscape */ __('Mode'); ?></th>
        <th class="data-grid-th" style="width: 40%;"><?= /* @noEscape */ __('Value'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($element->getSpecifics() as $index => $specific) { ?>
        <tr style="height: 25px;"  class="<?php
        /* @noEscape */ $element->getAdditionalClass($specific); ?>">
            <td style="vertical-align:top;">
                <?php
                echo $element->getAttributeIdHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getAttributeNameHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getAttributeTypeHiddenHtml($index, $specific); ?>
                <?php
                echo $element->getModeHtml($index); ?>
                <?php
                echo $element->getAttributeTitleLabelHtml($index, $specific); ?>
                <?php
                //echo $element->getTitleTooltip($specific);//TODO? ?>
            </td>
            <td style="vertical-align:top;">
                <?php
                echo $element->getValueModeSelectHtml($index, $specific); ?>
            </td>
            <td style="width: 100%; vertical-align:top; text-align: left;">
                <?php
                echo $element->getValueTemuRecommendedHtml($index, $specific); ?>
                <?php
                echo $element->getValueCustomValueHtml($index, $specific); ?>
                <?php
                echo $element->getValueCustomAttributeHtml($index, $specific); ?>
            </td>
        </tr>
        <?php
    } ?>
    </tbody>
</table>
