<?php
/** @var \Magento\Backend\Block\Template $block */
$parentBlock = $block->getParentBlock();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Temu/Category/Attribute/Validation/Grid": {
            "grid_id": "<?= $block->escapeHtml($parentBlock->getGridSelectorId()) ?>",
            "progress_bar_id": "<?= $block->escapeHtml($parentBlock->getProgressBarSelectorId()) ?>",
            "validate_url": "<?= $block->escapeHtml($parentBlock->getValidateUrl()) ?>",
            "reload_grid_url": "<?= $block->escapeHtml($parentBlock->getReloadGridUrl()) ?>"
        }
    }
}
</script>
