<?php

/** @var \M2E\Temu\Block\Adminhtml\Order\View\Form $block */

?>

<div class="row">
    <div class="col-m-6" style="padding-right:21px">
        <div class="fieldset-wrapper" id="magento_block_orders_general">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="admin__collapsible-title">
                    <span><?= /* @noEscape */ __(\M2E\Temu\Helper\Module::getChannelTitle() . ' Order'); ?> #<?= /* @noEscape */ $block->order->getChannelOrderId() ?></span>
                </strong>
                <div class="form-buttons"></div>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">
                    <table class="order-info form-list">
                        <tbody>
                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Magento Order #') ?></td>
                            <td class="value">
                                <strong>
                                    <?php
                                    if ($block->order->getMagentoOrderId() !== null) : ?>
                                        <a
                                            href="<?= /* @noEscape */ $block->getUrl(
                                                'sales/order/view/',
                                                ['order_id' => $block->order->getMagentoOrderId()]
                                            ); ?>" target="_blank">
                                            <?= /* @noEscape */ $block->realMagentoOrderId; ?>
                                        </a>
                                    <?php
                                    else : ?>
                                        <?= /* @noEscape */ __('N/A'); ?>
                                    <?php
                                    endif; ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Purchase Create Time'); ?></td>
                            <td class="value">
                                <strong>
                                    <?= /* @noEscape */ $block->formatDate(
                                        $block->order->getPurchaseDate()->format('Y-m-d H:i:s'),
                                        \IntlDateFormatter::MEDIUM,
                                        true
                                    ); ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Purchase Update Time'); ?></td>
                            <td class="value">
                                <strong>
                                    <?= /* @noEscape */ $block->formatDate(
                                        $block->order->getChannelUpdateDate()->format('Y-m-d H:i:s'),
                                        \IntlDateFormatter::MEDIUM,
                                        true
                                    ); ?>
                                </strong>
                            </td>
                        </tr>

                        <?php
                        if ($block->order->getReservationStartDate() !== '') : ?>
                            <tr>
                                <td class="label"><?= /* @noEscape */ __('Reservation Time') ?></td>
                                <td class="value">
                                    <strong>
                                        <?= /* @noEscape */ $block->formatDate(
                                            $block->order->getReservationStartDate(),
                                            \IntlDateFormatter::MEDIUM,
                                            true
                                        ); ?>
                                    </strong></td>
                            </tr>
                        <?php
                        endif; ?>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Order Status') ?></td>
                            <td class="value">
                                <strong>
                                    <span style="color: <?= /* @noEscape */ $block->getOrderStatusColor() ?>">
                                        <b><?= /* @noEscape */ $block->getOrderStatusLabel() ?></b>
                                    </span>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Account'); ?></td>
                            <td class="value">
                                <strong>

                                    <?php
                                    if (!$block->order->getAccount()->getId()) { ?>
                                        <span style="color: red;"><?= /* @noEscape */ __('Deleted'); ?></span>

                                    <?php
                                    } else { ?>
                                        <a href="<?= /* @noEscape */ $block->getAccountEditUrl() ?>" target="_blank"><?= \M2E\Core\Helper\Data::escapeHtml(
                                                $block->order->getAccount()->getTitle()
                                            ); ?></a>

                                    <?php
                                    } ?>

                                </strong>
                            </td>
                        </tr>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    <div class="col-m-6">
        <div class="fieldset-wrapper" id="magento_block_orders_buyer" style="min-height: 330px">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="admin__collapsible-title"><?= /* @noEscape */ __('Buyer Information'); ?></strong>
                <div style="float: right; margin-bottom: -15px; margin-top: -5px;">
                    <?= /* @noEscape */ $block->getChildHtml('edit_shipping_info'); ?>
                </div>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div id="shipping_address_container" class="hor-scroll">
                    <?= /* @noEscape */ $block->getChildHtml('shipping_address'); ?>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-m-6" style="margin-top: 30px;padding-right:21px">
        <div class="fieldset-wrapper" id="magento_block_orders_payment">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="icon-head head-edit-form fieldset-legend">
                <span>
                    <?= /* @noEscape */ __('Payment Information'); ?>
                </span>
                </strong>
                <div class="form-buttons"></div>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <table class="order-info form-list">
                        <tbody>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Order Currency'); ?></td>
                            <td class="value">
                                <strong>
                                    <?= \M2E\Core\Helper\Data::escapeHtml(
                                        $block->order->getCurrency()
                                    ); ?>
                                </strong>

                                <?php
                                if (!$block->isCurrencyAllowed()) {
                                    /* @noEscape */ echo '<br/><b>' . __('Attention!') . '</b> '
                                        . __('Order Currency is not enabled in Magento. Please, enable it in ')
                                        . '<i>' . __(
                                            'Stores > Settings > Configuration > General > Currency Setup.'
                                        ) . '</i>';
                                } elseif (!$block->hasCurrencyConversionRate()) {
                                    /* @noEscape */ echo '<br/><b>' . __('Attention!') . '</b> '
                                        . __(
                                            'There\'s no rate for Order Currency in Magento. Please, add Currency convert rate in '
                                        )
                                        . '<i>' . __('Stores > Currency > Currency Rates.') . '</i>';
                                }
                                ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <div class="col-m-6" style="margin-top: 30px">
        <div class="fieldset-wrapper" id="magento_block_orders_shipping">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="icon-head head-edit-form fieldset-legend">
                    <span><?= /* @noEscape */ __('Shipping & Handling Information'); ?></span>
                </strong>
                <div class="form-buttons"></div>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                <div class="hor-scroll">

                    <table class="order-info form-list">
                        <tbody>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Ship By Date'); ?></td>
                            <td class="value">
                                <strong>
                                    <?php
                                    if (empty($block->order->getShipByDate())) : ?>
                                        <?= /* @noEscape */ __('N/A'); ?>
                                    <?php
                                    else : ?>
                                        <?= /* @noEscape */ $block->formatDate(
                                            $block->order->getShipByDate(),
                                            \IntlDateFormatter::MEDIUM,
                                            true
                                        ); ?>
                                    <?php
                                    endif; ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Shipping Service'); ?></td>
                            <td class="value">
                                <strong>
                                    <?php
                                    if ($block->order->getShippingService() == '') { ?>
                                        <?= /* @noEscape */ __('N/A'); ?>
                                    <?php
                                    } else { ?>
                                        <?= \M2E\Core\Helper\Data::escapeHtml(
                                            $block->order->getShippingService()
                                        ); ?>
                                    <?php
                                    } ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?= /* @noEscape */ __('Shipping Cost'); ?></td>
                            <td class="value">
                                <strong>
                                    <?= /* @noEscape */ $block->formatPrice(
                                        $block->order->getCurrency(),
                                        $block->order->getShippingPrice()
                                    ) ?>
                                </strong>
                            </td>
                        </tr>

                        <?php
                        if ($block->order->getShipByDate() !== null) { ?>
                            <tr>
                                <td class="label"><?= /* @noEscape */ __('Shipping Time'); ?></td>
                                <td class="value"><strong>
                                        <?= /* @noEscape */ $block->formatDate(
                                            $block->order->getShippingTime(),
                                            \IntlDateFormatter::MEDIUM,
                                            true
                                        ); ?></strong></td>
                            </tr>
                        <?php
                        } ?>

                        <?php
                        if (count($block->order->getShippingTrackingDetails())) { ?>
                            <tr>
                                <td class="grid" colspan="2">
                                    <br/>
                                    <h4><?= /* @noEscape */ __('Tracking Details'); ?></h4>
                                    <table class="data-grid " cellpadding="0" cellspacing="0">
                                        <thead>
                                        <tr class="headings">
                                            <th class="data-grid-th"><?= /* @noEscape */ __('Carrier'); ?></th>
                                            <th class="data-grid-th"><?= /* @noEscape */ __('Number'); ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        <?php
                                        foreach (
                                            $block->order->getShippingTrackingDetails() as $key => $trackingDetail
                                        ) { ?>
                                            <tr class="<?= /* @noEscape */ $key % 2 ? 'odd' : 'even' ?>">
                                                <td><?= /* @noEscape */ $trackingDetail['supplier_name']; ?></td>
                                                <td><?= /* @noEscape */ $trackingDetail['tracking_number']; ?></td>
                                            </tr>
                                        <?php
                                        } ?>

                                        </tbody>
                                    </table>
                                </td>
                            </tr>

                        <?php
                        } ?>

                        <?php
                        if ($childHtml = $block->getChildHtml('resubmit_shipping_info')) : ?>
                            <tr>
                                <td></td>
                                <td class="value" style="padding-top: 10px;">
                                    <?= /* @noEscape */ $childHtml; ?>
                                </td>
                            </tr>
                        <?php
                        endif; ?>

                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>
</div>
<div class="row">
    <div class="col-m-12">
        <div class="fieldset-wrapper" id="magento_block_orders_transaction">
            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title" style="margin-bottom: 0">
                <strong class="admin__collapsible-title">
                    <span><?= /* @noEscape */ __('Transaction Item(s)') ?></span>
                </strong>
            </div>

            <div class="fieldset-wrapper-content admin__fieldset-wrapper-content grid np">
                <?= /* @noEscape */ $block->getChildHtml('item'); ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-m-6" style="padding-right:21px">
        <div class="fieldset-wrapper" id="magento_block_orders_history">
            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="admin__collapsible-title"><span><?= /* @noEscape */ __('Custom Notes'); ?></span></strong>
                <div class="form-buttons"></div>
            </div>

            <div class="fieldset">
                <?= /* @noEscape */ $block->getChildHtml('order_note_grid'); ?>
                <?= /* @noEscape */ $block->getChildHtml('add_note_button'); ?>
            </div>

        </div>

        <?php
        $checkoutMessage = $block->order->getBuyerMessage() ?>

        <?php
        if (!empty($checkoutMessage)) : ?>
            <div class="fieldset-wrapper" id="magento_block_orders_message">
                <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                    <strong class="admin__collapsible-title">
                    <span>
                        <?= /* @noEscape */ __('Checkout Message From Buyer'); ?>
                    </span>
                    </strong>
                    <div class="form-buttons"></div>
                </div>

                <div class="fieldset-wrapper-content admin__fieldset-wrapper-content">
                    <?= \M2E\Core\Helper\Data::escapeHtml($checkoutMessage); ?>
                </div>

            </div>
        <?php
        endif; ?>

        <div class="fieldset-wrapper" id="magento_block_orders_history">

            <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
                <strong class="admin__collapsible-title"><span><?= /* @noEscape */ __('Order Log'); ?></span></strong>
                <div class="form-buttons"></div>
            </div>

            <a name="order_log"></a>

            <div class="fieldset">
                <?= /* @noEscape */ $block->getChildHtml('log'); ?>
            </div>

        </div>

    </div>
    <div class="col-m-6 fieldset-wrapper">

        <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
            <strong><span><?= /* @noEscape */ __('Order Totals'); ?></span></strong>
        </div>

        <div class="Temu-order-totals">
            <table class="order-info form-list">
                <tbody>

                <tr>
                    <td class="label">
                        <?php  /* @noEscape */ echo __('Subtotal'); ?>
                    </td>
                    <td><span class="price">
                            <?= /* @noEscape */ $block->formatPrice(
                                $block->order->getCurrency(),
                                $block->getSubtotalPrice()
                            ); ?>
                        </span>
                    </td>
                </tr>

                <tr>
                    <td class="label">
                        <?= /* @noEscape */ __('Shipping & Handling'); ?>
                    </td>
                    <td><span class="price"><?= /* @noEscape */ $block->formatPrice(
                                $block->order->getCurrency(),
                                $block->getShippingPrice()
                            ); ?></span></td>
                </tr>

                <tr>
                    <td class="label"><?= /* @noEscape */ __('Tax') ?></td>
                    <td><span class="price"><?= /* @noEscape */ $block->formatPrice(
                                $block->order->getCurrency(),
                                $block->getTaxAmount()
                            ); ?></span></td>
                </tr>

                <tr>
                    <?php if ($block->order->hasPriceDiscount()): ?>
                        <td class="label"><?= /* @noEscape */ __('Discount') ?></td>
                        <td><span class="price"><?= /* @noEscape */ $block->formatPrice(
                                    $block->order->getCurrency(),
                                    $block->order->getPriceDiscount()
                                ); ?></span></td>
                    <?php endif; ?>
                </tr>

                </tbody>

                <tfoot>

                <tr>
                    <td class="label">
                        <strong><big><?= /* @noEscape */ __('Grand Total') ?></big></strong>
                    </td>
                    <td class="emph"><big><strong><span class="price"><?= /* @noEscape */ $block->formatPrice(
                                        $block->order->getCurrency(),
                                        $block->getGrandTotal()
                                    ); ?></span></strong></big></td>
                </tr>

                </tfoot>
            </table>

        </div>
    </div>
</div>
