<?php

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \M2E\Temu\Block\Adminhtml\Listing\View\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>

<style type="text/css">

    div.listing-view-header {
        margin-bottom: 30px !important;
        padding: 10px 15px !important;
    }

    div.listing-view-header span.label {
        font-weight: bold;
    }

    div.listing-view-header span.value {
        color: #8e9393;
    }

    div.listing-view-header ul {
        text-align: justify;
        line-height: 0;
        font-size: 1px;
    }

    div.listing-view-header ul:after {
        width: 100%;
        height: 0;
        visibility: hidden;
        overflow: hidden;
        content: '';
        display: inline-block;
    }

    div.listing-view-header ul li {
        display: inline-block;
        text-align: left;
        line-height: normal;
        font-size: 12px;
        vertical-align: top;
    }

</style>

<div class="Temu-box-style listing-view-header">
    <ul>
        <?php
        if (!$block->isListingViewMode()) : ?>
            <li>
                <label>
                <span class="label">
                    <?php  /* @noEscape */ echo __('Listing'); ?>:&nbsp;
                </span>
                    <span class="value">
                    <?php echo $escaper->escapeHtml($block->getProfileTitle()); ?>
                </span>
                </label>
            </li>
        <?php
        endif; ?>
        <li>
            <label>
                <span class="label">
                    <?php /* @noEscape */ echo __('Account'); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $escaper->escapeHtml($block->getAccountTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php /* @noEscape */ echo __('Site'); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $escaper->escapeHtml($block->getSiteTitle()); ?>
                </span>
            </label>
        </li>
        <li>
            <label>
                <span class="label">
                    <?php  /* @noEscape */ echo __('Magento Store View'); ?>:&nbsp;
                </span>
                <span class="value">
                    <?php echo $escaper->escapeHtml($block->getStoreViewBreadcrumb(false)); ?>
                </span>
            </label>
        </li>
    </ul>
</div>
