<?php

/** @var \M2E\Temu\Block\Adminhtml\Template\Category\Chooser\Edit $block */

$selectedCategory = $block->getSelectedCategory();
?>

<style>

    .Temu-tabs-horizontal + div .ui-tabs-panel {
        margin-top: 10px;
    }

    #selected_category_container {
        border: 1px solid #e3e3e3;
        background-color: #ffffff;
        margin-bottom: 30px;
        padding: 1em .5em 1em 1.8rem;
    }

    #selected_category_container.flex-row {
        display: flex;
        gap: 10px;
    }

    #chooser_browser {
        white-space: nowrap;
        overflow: hidden;
        overflow-x: auto;
    }

    #chooser_tabs_container {
        height: 250px;
    }

    #chooser_search_results {
        height: 239px;
        overflow: auto;
        margin-top: 16px;
        border: 1px solid #e3e3e3;
    }

    #chooser_search_input_container {
        height: 23px;
    }

    #chooser_search_input_container > button:nth-child(2) {
        margin-right: -0.85em;
    }

    #query {
        width: 520px;
        box-sizing: border-box;
        border: 1px solid #adadad;
        border-radius: 1px;
        padding: 4px;
        color: #303030;
        background-color: #fff;
        font-weight: 500;
        font-size: 14px;
        height: 33px;
    }

    #search_results_table,
    #chooser_attributes_table {
        width: 100%;
    }

    #search_results_table tr:last-child td,
    #chooser_attributes_table tr:last-child td {
        border-bottom: 1px solid #fff;
    }

    #search_results_table td,
    #chooser_attributes_table td {
        padding: 1em 1.8rem !important;
        border-bottom: 1px solid #e3e3e3;
        background-color: #f8f8f8;
    }

    #chooser_recent {
        max-height: 240px;
        border: 1px solid #e3e3e3;
        overflow: auto;
    }

    #search_results_container {
        border: 1px solid #e3e3e3;
    }

    #search_results_container {
        margin-top: 5px;
    }

    #chooser_buttons_container {
        position: absolute;
        bottom: 0;
        right: 0;
        padding: 15px 24px;
    }

    #chooser_recent_table {
        width: 100%;
    }

    #chooser_recent_table td {
        padding: 1em 1.8rem !important;
        border-bottom: 1px solid #e3e3e3;
        background-color: #f8f8f8;
    }

    #chooser_recent_table tr:last-child td {
        border-bottom: 1px solid #f8f8f8;
    }

    .category-children-block {
        display: inline-block;
        margin-left: 10px;
    }

    tr.search_results_results_tr td {
        padding: 2px !important;
    }

    #chooser_attributes {
        max-height: 300px;
        overflow: auto;
        border: 1px solid #e3e3e3;
    }
    .flex-row {
        display: flex;
        align-items: center;
        gap: 15px;
    }
</style>

<div id="change_category_messaged_container"></div>

<div id="selected_category_container">
    <div class="flex-row">
        <span><strong><?= /* @noEscape */ __('Category'); ?></strong>:</span>

        <span id="selected_category_path"><?= /* @noEscape */ $block->getSelectedCategoryPathHtml(); ?></span>

        <a href="javascript:void(0)" id="category_reset_link" <?php
        if (empty($selectedCategory)) : ?>style="display: none"<?php
        endif; ?>
           onclick="TemuCategoryChooserObj.unSelectCategory()"><?= /* @noEscape */ __('Reset') ?></a>
    </div>
</div>

<input type="hidden" id="category_validation" value="" class="required-entry">
